import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export const LANGUAGES = [
  { code: 'es', label: 'Español', ocr: 'spa' }, { code: 'en', label: 'English', ocr: 'eng' },
  { code: 'fr', label: 'Français', ocr: 'fra' }, { code: 'it', label: 'Italiano', ocr: 'ita' },
  { code: 'pt', label: 'Português', ocr: 'por' }
] as const
export const FONTS = [
  { id: 'clean', label: 'Limpia', value: 'Inter, ui-sans-serif, system-ui, sans-serif' },
  { id: 'classic', label: 'Clásica', value: 'Georgia, Times New Roman, serif' },
  { id: 'rounded', label: 'Redondeada', value: 'Trebuchet MS, Arial Rounded MT Bold, sans-serif' },
  { id: 'modern', label: 'Moderna', value: 'Arial, Helvetica, sans-serif' },
  { id: 'mono', label: 'Monoespaciada', value: 'Courier New, monospace' }
] as const

type Language = typeof LANGUAGES[number]['code']
type Font = typeof FONTS[number]['id']
type Settings = { language: Language; font: Font }
type ContextValue = Settings & { setLanguage: (value: Language) => void; setFont: (value: Font) => void; t: (key: string) => string; categoryLabel: (value: string) => string; ocrLanguage: string }
const KEY = 'recetas-air:settings:v1'

const es: Record<string, string> = {
  recipes:'Mis recetas', favorites:'Favoritas', settings:'Ajustes', newRecipe:'Nueva receta', eyebrow:'TU RECETARIO PERSONAL', today:'¿Qué cocinamos hoy?', search:'Buscar por nombre o ingrediente...', import:'Importar receta', all:'Todas', allRecipes:'Todas las recetas', favoriteRecipes:'Recetas favoritas', recipe:'receta', recipesCount:'recetas', empty:'No hay recetas por aquí', emptyHint:'Prueba con otra búsqueda o crea una receta nueva.', localData:'Los datos se guardan únicamente en este dispositivo.', update:'Actualizar app', noIngredients:'Sin ingredientes todavía', oilFree:'Preparada sin aceite', temperature:'Temperatura', totalTime:'Tiempo total', ingredients:'Ingredientes', preparation:'Preparación', notes:'Notas del cocinero', delete:'Eliminar', edit:'Editar', close:'Cerrar', cancel:'Cancelar', save:'Guardar cambios', create:'Crear receta', name:'Nombre', nameHint:'(revísalo o escríbelo tú)', category:'Categoría', photo:'Foto de la receta', addPhoto:'Añadir foto', photoHint:'Desde la cámara o la fototeca', change:'Cambiar', remove:'Quitar', add:'Añadir', amount:'Cantidad', ingredient:'Ingrediente', steps:'Pasos', onePerLine:'(uno por línea)', notesField:'Notas', backup:'Copias', importText:'Desde texto', importPhoto:'Desde foto', organize:'Organizar receta', textRecipe:'Texto de la receta', recognizedText:'Texto reconocido (puedes corregirlo)', language:'Idioma', typography:'Tipografía', appearance:'APARIENCIA', settingsIntro:'Personaliza la aplicación. Los cambios se guardan en este dispositivo.', done:'Listo', takePhoto:'Hacer foto', photoLibrary:'Fototeca / álbum', searchWeb:'Buscar en internet', searchPhotos:'Buscar fotos de platos', usePhoto:'Usar foto', photoSource:'Ver fuente', searchAction:'Buscar', searchingPhotos:'Buscando fotos…', photoOptions:'opciones de fotos', noPhotoResults:'No se encontraron fotos. Prueba con otras palabras.', photoSearchError:'No se pudo conectar con el buscador. Comprueba Internet e inténtalo de nuevo.', savePhotoError:'No se pudo guardar esta imagen. Prueba con otra.', openverseNote:'Imágenes abiertas proporcionadas por Openverse. Consulta la fuente para ver su autor y licencia.'
}
const translations: Record<Language, Record<string, string>> = {
  es,
  en: {recipes:'My recipes',favorites:'Favorites',settings:'Settings',newRecipe:'New recipe',eyebrow:'YOUR PERSONAL COOKBOOK',today:'What are we cooking today?',search:'Search by name or ingredient...',import:'Import recipe',all:'All',allRecipes:'All recipes',favoriteRecipes:'Favorite recipes',recipe:'recipe',recipesCount:'recipes',empty:'No recipes here',emptyHint:'Try another search or create a new recipe.',localData:'Data is stored only on this device.',update:'Update app',noIngredients:'No ingredients yet',oilFree:'Prepared without oil',temperature:'Temperature',totalTime:'Total time',ingredients:'Ingredients',preparation:'Method',notes:'Cook’s notes',delete:'Delete',edit:'Edit',close:'Close',cancel:'Cancel',save:'Save changes',create:'Create recipe',name:'Name',nameHint:'(review or write it yourself)',category:'Category',photo:'Recipe photo',addPhoto:'Add photo',photoHint:'From camera or photo library',change:'Change',remove:'Remove',add:'Add',amount:'Amount',ingredient:'Ingredient',steps:'Steps',onePerLine:'(one per line)',notesField:'Notes',backup:'Backups',importText:'From text',importPhoto:'From photo',organize:'Organize recipe',textRecipe:'Recipe text',recognizedText:'Recognized text (you can edit it)',language:'Language',typography:'Typeface',appearance:'APPEARANCE',settingsIntro:'Customize the app. Changes are saved on this device.',done:'Done'},
  fr: {recipes:'Mes recettes',favorites:'Favoris',settings:'Réglages',newRecipe:'Nouvelle recette',eyebrow:'VOTRE LIVRE DE RECETTES',today:'Que cuisinons-nous aujourd’hui ?',search:'Rechercher par nom ou ingrédient...',import:'Importer une recette',all:'Toutes',allRecipes:'Toutes les recettes',favoriteRecipes:'Recettes favorites',recipe:'recette',recipesCount:'recettes',empty:'Aucune recette ici',emptyHint:'Essayez une autre recherche ou créez une recette.',localData:'Les données sont stockées uniquement sur cet appareil.',update:'Mettre à jour',noIngredients:'Aucun ingrédient',oilFree:'Préparée sans huile',temperature:'Température',totalTime:'Temps total',ingredients:'Ingrédients',preparation:'Préparation',notes:'Notes',delete:'Supprimer',edit:'Modifier',close:'Fermer',cancel:'Annuler',save:'Enregistrer',create:'Créer la recette',name:'Nom',nameHint:'(vérifiez ou écrivez-le)',category:'Catégorie',photo:'Photo de la recette',addPhoto:'Ajouter une photo',photoHint:'Appareil photo ou photothèque',change:'Changer',remove:'Retirer',add:'Ajouter',amount:'Quantité',ingredient:'Ingrédient',steps:'Étapes',onePerLine:'(une par ligne)',notesField:'Notes',backup:'Sauvegardes',importText:'Depuis un texte',importPhoto:'Depuis une photo',organize:'Organiser la recette',textRecipe:'Texte de la recette',recognizedText:'Texte reconnu (modifiable)',language:'Langue',typography:'Police',appearance:'APPARENCE',settingsIntro:'Personnalisez l’application. Les changements sont enregistrés sur cet appareil.',done:'Terminé'},
  it: {recipes:'Le mie ricette',favorites:'Preferite',settings:'Impostazioni',newRecipe:'Nuova ricetta',eyebrow:'IL TUO RICETTARIO',today:'Cosa cuciniamo oggi?',search:'Cerca per nome o ingrediente...',import:'Importa ricetta',all:'Tutte',allRecipes:'Tutte le ricette',favoriteRecipes:'Ricette preferite',recipe:'ricetta',recipesCount:'ricette',empty:'Nessuna ricetta qui',emptyHint:'Prova un’altra ricerca o crea una ricetta.',localData:'I dati sono salvati solo su questo dispositivo.',update:'Aggiorna app',noIngredients:'Nessun ingrediente',oilFree:'Preparata senza olio',temperature:'Temperatura',totalTime:'Tempo totale',ingredients:'Ingredienti',preparation:'Preparazione',notes:'Note',delete:'Elimina',edit:'Modifica',close:'Chiudi',cancel:'Annulla',save:'Salva modifiche',create:'Crea ricetta',name:'Nome',nameHint:'(controlla o scrivilo tu)',category:'Categoria',photo:'Foto della ricetta',addPhoto:'Aggiungi foto',photoHint:'Fotocamera o libreria foto',change:'Cambia',remove:'Rimuovi',add:'Aggiungi',amount:'Quantità',ingredient:'Ingrediente',steps:'Passaggi',onePerLine:'(uno per riga)',notesField:'Note',backup:'Backup',importText:'Da testo',importPhoto:'Da foto',organize:'Organizza ricetta',textRecipe:'Testo della ricetta',recognizedText:'Testo riconosciuto (modificabile)',language:'Lingua',typography:'Carattere',appearance:'ASPETTO',settingsIntro:'Personalizza l’app. Le modifiche sono salvate su questo dispositivo.',done:'Fatto'},
  pt: {recipes:'Minhas receitas',favorites:'Favoritas',settings:'Definições',newRecipe:'Nova receita',eyebrow:'O SEU LIVRO DE RECEITAS',today:'O que vamos cozinhar hoje?',search:'Pesquisar por nome ou ingrediente...',import:'Importar receita',all:'Todas',allRecipes:'Todas as receitas',favoriteRecipes:'Receitas favoritas',recipe:'receita',recipesCount:'receitas',empty:'Nenhuma receita aqui',emptyHint:'Tente outra pesquisa ou crie uma receita.',localData:'Os dados são guardados apenas neste dispositivo.',update:'Atualizar app',noIngredients:'Sem ingredientes',oilFree:'Preparada sem óleo',temperature:'Temperatura',totalTime:'Tempo total',ingredients:'Ingredientes',preparation:'Preparação',notes:'Notas',delete:'Eliminar',edit:'Editar',close:'Fechar',cancel:'Cancelar',save:'Guardar alterações',create:'Criar receita',name:'Nome',nameHint:'(reveja ou escreva você)',category:'Categoria',photo:'Foto da receita',addPhoto:'Adicionar foto',photoHint:'Câmara ou biblioteca de fotos',change:'Alterar',remove:'Remover',add:'Adicionar',amount:'Quantidade',ingredient:'Ingrediente',steps:'Passos',onePerLine:'(um por linha)',notesField:'Notas',backup:'Cópias',importText:'Do texto',importPhoto:'Da foto',organize:'Organizar receita',textRecipe:'Texto da receita',recognizedText:'Texto reconhecido (pode editar)',language:'Idioma',typography:'Tipo de letra',appearance:'APARÊNCIA',settingsIntro:'Personalize a aplicação. As alterações ficam guardadas neste dispositivo.',done:'Concluído'}
}
const categoryNames: Record<Language, Record<string, string>> = {
  es: {}, en: { Pollo:'Chicken', Carne:'Meat', Pescado:'Fish', 'Patatas y verduras':'Potatoes & vegetables', Huevos:'Eggs', Postres:'Desserts', Otros:'Other' },
  fr: { Pollo:'Poulet', Carne:'Viande', Pescado:'Poisson', 'Patatas y verduras':'Pommes de terre et légumes', Huevos:'Œufs', Postres:'Desserts', Otros:'Autres' },
  it: { Pollo:'Pollo', Carne:'Carne', Pescado:'Pesce', 'Patatas y verduras':'Patate e verdure', Huevos:'Uova', Postres:'Dolci', Otros:'Altro' },
  pt: { Pollo:'Frango', Carne:'Carne', Pescado:'Peixe', 'Patatas y verduras':'Batatas e legumes', Huevos:'Ovos', Postres:'Sobremesas', Otros:'Outros' }
}

const SettingsContext = createContext<ContextValue | null>(null)
export function SettingsProvider({ children }: { children: ReactNode }) {
  const saved = (() => { try { return JSON.parse(localStorage.getItem(KEY) ?? '{}') } catch { return {} } })()
  const [language, setLanguage] = useState<Language>(saved.language ?? 'es')
  const [font, setFont] = useState<Font>(saved.font ?? 'clean')
  useEffect(() => { localStorage.setItem(KEY, JSON.stringify({ language, font })); document.documentElement.lang = language; document.documentElement.style.setProperty('--app-font', FONTS.find(item => item.id === font)?.value ?? FONTS[0].value) }, [language, font])
  const t = (key: string) => translations[language][key] ?? es[key] ?? key
  const categoryLabel = (value: string) => categoryNames[language][value] ?? value
  return <SettingsContext.Provider value={{ language, font, setLanguage, setFont, t, categoryLabel, ocrLanguage: LANGUAGES.find(item => item.code === language)?.ocr ?? 'spa' }}>{children}</SettingsContext.Provider>
}
export function useSettings() { const value = useContext(SettingsContext); if (!value) throw new Error('SettingsProvider missing'); return value }
